version: '3.9'

services:
  db:
    container_name: socialpets_db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ejemplo

    volumes:
      - C:/DB/var/lib/postgresql/data:/var/lib/postgresql/data